[package]
name = "rewind"
default-run = "rewind"
version = "0.9.7"
edition = "2021"
license = "MIT"
description = "A transactional programming language with checkpoints and virtual I/O"

[dependencies]
ed25519-dalek = "=2.2.0"
sha2 = "=0.10.9"
serde_json = "=1.0.145"
semver = "=1.0.28"
serde = { version = "=1.0.228", features = ["derive", "rc"] }
getrandom = "=0.2.17"

[target.'cfg(unix)'.dependencies]
libc = "=0.2.189"

[lib]
name = "rewind"
path = "src/lib.rs"

[[bin]]
name = "rewind"
path = "src/main.rs"

[[bin]]
name = "rewindc"
path = "src/rewindc.rs"
